/* ************************************************************************** */
/*                                                                            */
/*                                                        :::      ::::::::   */
/*   main.c                                             :+:      :+:    :+:   */
/*                                                    +:+ +:+         +:+     */
/*   By: jalmeida <jalmeida@student.42.fr>          +#+  +:+       +#+        */
/*                                                +#+#+#+#+#+   +#+           */
/*   Created: 2020/10/29 16:08:04 by flemos-d          #+#    #+#             */
/*   Updated: 2020/11/02 21:55:43 by mchaveir         ###   ########.fr       */
/*                                                                            */
/* ************************************************************************** */

#include <stdio.h>
#include <string.h>
#include <unistd.h>

char    		*ft_strcpy(char *dest, char *src);
char			*ft_strncpy(char *dest, char *src, unsigned int n);
int				ft_str_is_alpha(char *str);
int				ft_str_is_numeric(char *str);
int 		    ft_str_is_lowercase(char *str);
int				ft_str_is_uppercase(char *str);
int				ft_str_is_printable(char *str);
char    		*ft_strupcase(char *str);
char			*ft_strlowcase(char *str);
char    		*ft_strcapitalize(char *str);
unsigned int	ft_strlcpy(char *dest, char *src, unsigned int size);
// void 			ft_putstr_non_printable(char *str);

int		main(void)
{
	printf("----- EX00: ft_strcpy -----\n");
	printf("Test:\n");
	char str1[20] = "C programming";
   	char *str2 = "This is a test";
	printf("dest: %s\n", str1);
	printf("src: %s\n", str2);
	printf("With strcpy:\n");
	strcpy(str1, str2);
	puts(str1);
	char str2b[20] = "C programming";
	printf("With ft_strcpy:\n");
   	char *str2c = "This is a test";
	ft_strcpy(str2b, str2c);
	puts(str2b);
	printf("\n");

	printf("----- EX01: ft_strncpy -----\n");
	printf("Test:\n");
	char str3[20] = "C programming";
	printf("dest: %s\n", str3);
	printf("src: %s\n", str2c);
	printf("size: 6\n");
	printf("With strncpy:\n");
	strncpy(str3, str2c, 6);
	puts(str3);
	char str3b[20] = "C programming";
	printf("With ft_strncpy:\n");
	ft_strncpy(str3b, str2c, 6);
	puts(str3b);
	printf("\n");

	printf("----- EX02 -----\n");
	printf("String that should return 0\n");
   	char *str4 = "Swim hard. Dream big!?";
	puts(str4);
	printf("%d\n", ft_str_is_alpha(str4));
	printf("String that should return 0\n");
   	char *str5 = "dewdew54343#^&*(";
	puts(str5);
	printf("%d\n", ft_str_is_alpha(str5));
	printf("String that should return 1\n");
	char *str6 = "Dimitri";
	puts(str6);
	printf("%d\n", ft_str_is_alpha(str6));
	printf("String empty that should return 1\n");
	char *str7 = "";
	puts(str7);
	printf("%d\n", ft_str_is_alpha(str7));
	printf("\n");
	printf("----- EX03 -----\n");
	printf("String that should return 0\n");
   	char *str8 = "4564&%$%$5465";
	puts(str8);
	printf("%d\n", ft_str_is_numeric(str8));
	printf("String that should return 0\n");
   	char *str9 = "910 910";
	puts(str9);
	printf("%d\n", ft_str_is_numeric(str9));
	printf("String that should return 1\n");
	char *str10 = "1";
	puts(str10);
	printf("%d\n", ft_str_is_numeric(str10));
	printf("String that should return 1\n");
	char *str11 = "1910165615665";
	puts(str11);
	printf("%d\n", ft_str_is_numeric(str11));
	printf("String empty that should return 1\n");
	char *str12 = "";
	puts(str12);
	printf("%d\n", ft_str_is_numeric(str12));
	printf("\n");
	printf("----- EX04 -----\n");
	printf("String that should return 0\n");
   	char *str13 = "swim hard dream big";
	puts(str13);
	printf("%d\n", ft_str_is_lowercase(str13));
	printf("String that should return 0\n");
   	char *str14 = "dewdew54343#^&*(";
	puts(str14);
	printf("%d\n", ft_str_is_lowercase(str14));
	printf("String that should return 1\n");
	char *str15 = "dimitri";
	puts(str15);
	printf("%d\n", ft_str_is_lowercase(str15));
	printf("String empty that should return 1\n");
	char *str16 = "";
	puts(str16);
	printf("%d\n", ft_str_is_lowercase(str16));
	printf("\n");
	printf("----- EX05 -----\n");
	printf("String that should return 0\n");
   	char *str17 = "SWIM HARD DREAM BIG";
	puts(str17);
	printf("%d\n", ft_str_is_uppercase(str17));
	printf("String that should return 0\n");
   	char *str18 = "DEDWED54343#^&*(";
	puts(str18);
	printf("%d\n", ft_str_is_uppercase(str18));
	printf("String that should return 1\n");
	char *str19 = "DIMITRI";
	puts(str19);
	printf("%d\n", ft_str_is_uppercase(str19));
	printf("String empty that should return 1\n");
	char *str20 = "";
	puts(str20);
	printf("%d\n", ft_str_is_uppercase(str20));
	printf("\n");
	printf("----- EX06: ft_str_is_printable -----\n");
	printf("String that should return 0\n");
   	char *str21 = "frefre§";
	puts(str21);
	printf("%d\n", ft_str_is_printable(str21));
	printf("String that should return 1\n");
	char *str22 = "DIMITRI";
	puts(str22);
	printf("%d\n", ft_str_is_printable(str22));
	printf("String that should return 1\n");
	char *str23 = "deshbfu3r3474@$&;:";
	puts(str23);
	printf("%d\n", ft_str_is_printable(str23));
	printf("String empty that should return 1\n");
	puts(str20);
	printf("%d\n", ft_str_is_printable(str20));
	printf("\n");
	printf("----- EX07 -----\n");
	char str24[6] = "Hello";
	puts(str24);
	puts(ft_strupcase(str24));
	char str25[7] = "t!es7";
	puts(str25);
	puts(ft_strupcase(str25));
	char str26[6] = "879f@";
	puts(str26);
	puts(ft_strupcase(str26));
	printf("\n");
	printf("----- EX08 -----\n");
	char str27[6] = "HEllo";
	puts(str27);
	puts(ft_strlowcase(str27));
	char str28[6] = "t!ES7";
	puts(str28);
	puts(ft_strlowcase(str28));
	char str29[6] = "879F@";
	puts(str29);
	puts(ft_strlowcase(str29));
	printf("");
	printf("----- EX09 -----\n");
	char str30[] = "Salut, comment tu vas ? 42mots quarante-deux; cinquante+et+un";
	puts(str30);
	printf("%s\n", ft_strcapitalize(str30));
	char str31[] = "42this is a trap";
	puts(str31);
	printf("%s\n", ft_strcapitalize(str31));
	char str32[] = " 42this is a trap";
	puts(str32);
	printf("%s\n", ft_strcapitalize(str32));
	printf("\n");
	/*printf("----- EX10: ft_strlcpy -----\n");
	printf("Test when strlen(src) > size:\n");
	char str33[20] = "C programming";
   	char *str34 = "This is a test";
	printf("dest: %s\n", str33);
	printf("src: %s\n", str34);
	printf("size: 6\n");
	printf("With strlcpy:\n");
	int length1 = 0;
	length1 = strlcpy(str33, str34, 6);
	puts(str33);
	printf("Length of src: %d\n", length1);
	char str35[20] = "C programming";
	printf("With ft_strlcpy:\n");
   	char *str36 = "This is a test";
	int length2 = 0;
	length2 = ft_strlcpy(str35, str36, 6);
puts(str35);
	printf("Length of src: %d\n", length2);
	printf("\n");
	printf("Test when strlen(src) < size:\n");
	char str33b[20] = "C programming";
   	char *str34b = "This i";
	printf("dest: %s\n", str33b);
	printf("src: %s\n", str34b);
	printf("size: 6\n");
	printf("With strlcpy:\n");
	int length1b = 0;
	length1b = strlcpy(str33b, str34b, 6);
	puts(str33b);
	printf("Length of src: %d\n", length1b);
	char str35b[20] = "C programming";
	printf("With ft_strlcpy:\n");
   	char *str36b = "This i";
	int length2b = 0;
	length2b = ft_strlcpy(str35b, str36b, 6);
	puts(str35b);
	printf("Length of src: %d\n", length2b);
	printf("\n");
	printf("Test when strlen(src) = size:\n");
	char str33c[20] = "C programming";
   	char *str34c = "This ";
	printf("dest: %s\n", str33c);
	printf("src: %s\n", str34c);
	printf("size: 6\n");
	printf("With strlcpy:\n");
	int length1c = 0;
	length1c = strlcpy(str33c, str34c, 6);
	puts(str33c);
	printf("Length of src: %d\n", length1c);
	char str35c[20] = "C programming";
	printf("With ft_strlcpy:\n");
   	char *str36c = "This ";
	int length2c = 0;
	length2c = ft_strlcpy(str35c, str36c, 6);
	puts(str35c);
	printf("Length of src: %d\n", length2c);
	printf("\n"); */
	// printf("----- EX11: ft_putstr_non_printable -----\n");
	// printf("With the break line (in hex, 0a):\n");
	// char *str37 = "Coucou\ntu vas bien ?";
	// ft_putstr_non_printable(str37);
	// printf("\n");
	// printf("With the escape (in hex, 1b):\n");
	// char *str38 = "Coucou\etu vas bien ?";
	// ft_putstr_non_printable(str38);
	// printf("\n");
	// printf("With the backspace character (in hex, 08):\n");
	// char *str39 = "Coucou\btu vas bien ?";
	// ft_putstr_non_printable(str39);
	// printf("\n");
	// return (0);
}
